//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessEngineClassLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessEngineClassLibrary.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackBishop.png.
        /// </summary>
        public static string bBishop {
            get {
                return ResourceManager.GetString("bBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackKing.png.
        /// </summary>
        public static string bKing {
            get {
                return ResourceManager.GetString("bKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackKnight.png.
        /// </summary>
        public static string bKnight {
            get {
                return ResourceManager.GetString("bKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackPawn.png.
        /// </summary>
        public static string bPawn {
            get {
                return ResourceManager.GetString("bPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackQueen.png.
        /// </summary>
        public static string bQueen {
            get {
                return ResourceManager.GetString("bQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackRook.png.
        /// </summary>
        public static string bRook {
            get {
                return ResourceManager.GetString("bRook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string PieceHeight {
            get {
                return ResourceManager.GetString("PieceHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string PieceWidth {
            get {
                return ResourceManager.GetString("PieceWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.Pictures.
        /// </summary>
        public static string ResourcePath {
            get {
                return ResourceManager.GetString("ResourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiteBishop.png.
        /// </summary>
        public static string wBishop {
            get {
                return ResourceManager.GetString("wBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiteKing.png.
        /// </summary>
        public static string wKing {
            get {
                return ResourceManager.GetString("wKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiteKnight.png.
        /// </summary>
        public static string wKnight {
            get {
                return ResourceManager.GetString("wKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whitePawn.png.
        /// </summary>
        public static string wPawn {
            get {
                return ResourceManager.GetString("wPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiteQueen.png.
        /// </summary>
        public static string wQueen {
            get {
                return ResourceManager.GetString("wQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whiteRook.png.
        /// </summary>
        public static string wRook {
            get {
                return ResourceManager.GetString("wRook", resourceCulture);
            }
        }
    }
}
